export const LABELS = {
  DASHBOARD: "แดชบอร์ด",
  CHATS: "แชทร้านค้า",
  STORES: "จัดการร้านค้า",
  NEW_MESSAGES: "ข้อความเข้าใหม่",
  FOLLOW_UP: "ต้องติดตาม",
  NOTIFIED: "เตือนแล้ว",
  VIEW_CONVERSATION: "ดูบทสนทนา",
  OPEN_LINE_OA: "เปิด LINE OA",
  OPEN_LINE_OA_MANAGER: "เปิด LINE OA Manager",
  OPEN_LINE_OA_PROFILE: "เปิดหน้าโปรไฟล์ LINE OA",
  VIEW_ORIGINAL_MESSAGE: "ดูข้อความภาษาเดิม",
  RESET_COLUMN_SIZES: "รีเซ็ตขนาดคอลัมน์",
  TEST_CONNECTION: "ทดสอบการเชื่อมต่อ",
  COPY_WEBHOOK_URL: "คัดลอก Webhook URL",
  REGENERATE_WEBHOOK_URL: "สร้าง Webhook URL ใหม่",
  DEACTIVATE: "ปิดใช้งาน",
  DELETE_LINE_OA: "ลบ LINE OA",
  GLOBAL_SEARCH_PLACEHOLDER: "ค้นหาลูกค้า ร้านค้า หรือข้อความ…",
  LOGOUT: "ออกจากระบบ",
};