ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

ALTER TYPE "RegistrationRequestStatus" ADD VALUE IF NOT EXISTS 'APPROVED';

ALTER TABLE "RegistrationRequest"
  ADD COLUMN "passwordHash" TEXT,
  ALTER COLUMN "phone" DROP NOT NULL,
  ALTER COLUMN "firstName" DROP NOT NULL,
  ALTER COLUMN "lastName" DROP NOT NULL,
  ALTER COLUMN "employeeId" DROP NOT NULL,
  ALTER COLUMN "position" DROP NOT NULL;
