name: line_oa_chat_hub
description: Android client for OPPO LINE OA Chat.
publish_to: none
version: 1.0.4+5

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  http: ^1.2.2
  http_parser: ^4.1.2
  connectivity_plus: ^6.1.0
  image_picker: '>=1.1.2 <1.2.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  image_picker_android: 0.8.12+13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/line_contact_qr.jpg
    - assets/images/LOGO_OBS.png
