name: line_oa_chat_hub
description: Android client for OPPO LINE OA Chat.
publish_to: none
version: 1.1.5+25

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  http: ^1.2.2
